version: '3.8'
services:
  web:
    container_name: vtb_web
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${FAST_API_PORT}:8000"
    restart: on-failure
    command: bash -c "alembic revision -m 'create tables'&&alembic upgrade head&&uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    networks:
      - main-vtb
    depends_on:
      - db
  db:
    container_name: vtb_postgresql
    image: postgres:11
    env_file: .env
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    networks:
      - main-vtb
    restart: always

networks:
  main-vtb:
    driver: bridge