"""create tables

Revision ID: 0041ecad3a4b
Revises: 3ed27444ba17
Create Date: 2021-10-09 17:36:38.108604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0041ecad3a4b'
down_revision = '3ed27444ba17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
