"""create tables

Revision ID: 00a50c763094
Revises: c50b73d3c26b
Create Date: 2021-10-09 14:55:35.050628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a50c763094'
down_revision = 'c50b73d3c26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
