"""create tables

Revision ID: 0366586feda1
Revises: 55bc34391473
Create Date: 2021-10-09 17:35:55.046314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0366586feda1'
down_revision = '55bc34391473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
