"""create tables

Revision ID: 0494b8da9a4d
Revises: 08162a057a6c
Create Date: 2021-10-09 17:28:50.318224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0494b8da9a4d'
down_revision = '08162a057a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
