"""create tables

Revision ID: 04efdc98c626
Revises: ea577249414d
Create Date: 2021-10-09 17:39:56.104744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04efdc98c626'
down_revision = 'ea577249414d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
