"""create tables

Revision ID: 06f02c42ad46
Revises: c739473f10b9
Create Date: 2021-10-09 17:19:23.931775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f02c42ad46'
down_revision = 'c739473f10b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
