"""create tables

Revision ID: 0733dfffc200
Revises: 2e1c024aebad
Create Date: 2021-10-09 09:48:41.062394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0733dfffc200'
down_revision = '2e1c024aebad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
