"""create tables

Revision ID: 07d7d6ac5180
Revises: d0da467bf1d0
Create Date: 2021-10-09 14:31:39.278518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d7d6ac5180'
down_revision = 'd0da467bf1d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
