"""create tables

Revision ID: 08162a057a6c
Revises: 7ba97ba170d4
Create Date: 2021-10-09 17:27:45.437749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08162a057a6c'
down_revision = '7ba97ba170d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
