"""create tables

Revision ID: 08fc9a7623b6
Revises: ac2da1b556de
Create Date: 2021-10-09 10:22:09.235270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08fc9a7623b6'
down_revision = 'ac2da1b556de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
