"""create tables

Revision ID: 094739643b2c
Revises: 9df161f771e4
Create Date: 2021-10-09 14:42:48.944112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094739643b2c'
down_revision = '9df161f771e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
