"""create tables

Revision ID: 0aba2ae9e14d
Revises: 74660779f5f5
Create Date: 2021-10-09 23:49:51.543608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aba2ae9e14d'
down_revision = '74660779f5f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
