"""create tables

Revision ID: 0b723ec44f7f
Revises: cd2c60df7506
Create Date: 2021-10-09 10:23:37.959828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b723ec44f7f'
down_revision = 'cd2c60df7506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
