"""create tables

Revision ID: 0e7a03c09e51
Revises: 00a50c763094
Create Date: 2021-10-09 14:56:27.049380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7a03c09e51'
down_revision = '00a50c763094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
