"""create tables

Revision ID: 0f6f49a718b0
Revises: b18996f507fd
Create Date: 2021-10-09 14:51:35.323378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6f49a718b0'
down_revision = 'b18996f507fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
