"""create tables

Revision ID: 118e2c60723f
Revises: 0041ecad3a4b
Create Date: 2021-10-09 17:36:55.741545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118e2c60723f'
down_revision = '0041ecad3a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
