"""create tables

Revision ID: 14179c0500b4
Revises: f2dbb3dba1d2
Create Date: 2021-10-09 17:19:07.777096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14179c0500b4'
down_revision = 'f2dbb3dba1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
