"""create tables

Revision ID: 1473c2f03563
Revises: 1c483c5d0ecc
Create Date: 2021-10-09 23:20:46.711598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1473c2f03563'
down_revision = '1c483c5d0ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
