"""create tables

Revision ID: 17d6667e389c
Revises: 54b40d987eda
Create Date: 2021-10-09 15:00:34.908138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d6667e389c'
down_revision = '54b40d987eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
