"""create tables

Revision ID: 1ac7920bde5d
Revises: c07aed9811c6
Create Date: 2021-10-09 14:31:27.556951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac7920bde5d'
down_revision = 'c07aed9811c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
