"""create tables

Revision ID: 1c483c5d0ecc
Revises: e1a850ee2cf3
Create Date: 2021-10-09 23:14:36.447898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c483c5d0ecc'
down_revision = 'e1a850ee2cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
