"""create tables

Revision ID: 1c9685fe0e47
Revises: 971a8f3da787
Create Date: 2021-10-09 17:33:11.605477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c9685fe0e47'
down_revision = '971a8f3da787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
