"""create tables

Revision ID: 21289e12e906
Revises: ed486f37e4cf
Create Date: 2021-10-09 17:34:38.221439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21289e12e906'
down_revision = 'ed486f37e4cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
