"""create tables

Revision ID: 216537fa5862
Revises: 2c0e7c137d87
Create Date: 2021-10-09 09:40:25.592067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216537fa5862'
down_revision = '2c0e7c137d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
