"""create tables

Revision ID: 24142aa336c7
Revises: 0aba2ae9e14d
Create Date: 2021-10-09 23:50:52.574976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24142aa336c7'
down_revision = '0aba2ae9e14d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
