"""create tables

Revision ID: 26b148e8ceef
Revises: 9ffa71ca73a4
Create Date: 2021-10-09 20:42:10.956776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b148e8ceef'
down_revision = '9ffa71ca73a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
