"""create tables

Revision ID: 2c0e7c137d87
Revises: 9e5d8a92311c
Create Date: 2021-10-09 09:37:16.764524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0e7c137d87'
down_revision = '9e5d8a92311c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
