"""create tables

Revision ID: 2c88a28a2982
Revises: cf70ecc07a62
Create Date: 2021-10-09 09:43:33.096526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c88a28a2982'
down_revision = 'cf70ecc07a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
