"""create tables

Revision ID: 2e1c024aebad
Revises: dbf599af193b
Create Date: 2021-10-09 09:47:37.159753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1c024aebad'
down_revision = 'dbf599af193b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
