"""create tables

Revision ID: 2f2c54e511be
Revises: 33fad33f04fe
Create Date: 2021-10-09 17:31:02.152201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f2c54e511be'
down_revision = '33fad33f04fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
