"""create tables

Revision ID: 3028b658035f
Revises: 4c5b4b6d2b19
Create Date: 2021-10-09 23:59:06.985314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3028b658035f'
down_revision = '4c5b4b6d2b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
