"""create tables

Revision ID: 3096c032e882
Revises: f50071b9e8ad
Create Date: 2021-10-09 17:36:14.273383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3096c032e882'
down_revision = 'f50071b9e8ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
