"""create tables

Revision ID: 31a5ed32fe8f
Revises: 24142aa336c7
Create Date: 2021-10-09 23:53:39.473799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31a5ed32fe8f'
down_revision = '24142aa336c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
