"""create tables

Revision ID: 33fad33f04fe
Revises: 0494b8da9a4d
Create Date: 2021-10-09 17:29:55.555317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33fad33f04fe'
down_revision = '0494b8da9a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
