"""create tables

Revision ID: 345cfc88f5a8
Revises: dacb50e8ab1d
Create Date: 2021-10-09 23:31:32.849626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345cfc88f5a8'
down_revision = 'dacb50e8ab1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('user_pk', sa.Integer(), nullable=True))
    op.drop_constraint('dataset_user_id_fkey', 'dataset', type_='foreignkey')
    op.create_foreign_key(None, 'dataset', 'user', ['user_pk'], ['id'])
    op.drop_column('dataset', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dataset', type_='foreignkey')
    op.create_foreign_key('dataset_user_id_fkey', 'dataset', 'user', ['user_id'], ['id'])
    op.drop_column('dataset', 'user_pk')
    # ### end Alembic commands ###
