"""create tables

Revision ID: 39a1e7c1a463
Revises: 590719613023
Create Date: 2021-10-09 15:00:43.710602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a1e7c1a463'
down_revision = '590719613023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
