"""create tables

Revision ID: 3ed27444ba17
Revises: f1bb404fd447
Create Date: 2021-10-09 17:36:27.146514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed27444ba17'
down_revision = 'f1bb404fd447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
