"""create tables

Revision ID: 3ff1fd7a973c
Revises: 2a22f8558185
Create Date: 2021-10-09 17:18:51.195342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff1fd7a973c'
down_revision = '2a22f8558185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
