"""create tables

Revision ID: 41ea314c3a05
Revises: b8ca9ee43a99
Create Date: 2021-10-09 10:27:17.610147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ea314c3a05'
down_revision = 'b8ca9ee43a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
