"""create tables

Revision ID: 46936303b3ec
Revises: 41ea314c3a05
Create Date: 2021-10-09 11:04:30.993838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46936303b3ec'
down_revision = '41ea314c3a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
