"""create tables

Revision ID: 47b0416c7220
Revises: 118e2c60723f
Create Date: 2021-10-09 17:37:24.742741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b0416c7220'
down_revision = '118e2c60723f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
