"""create tables

Revision ID: 48e1bad1ca49
Revises: 7bb76f4dedb3
Create Date: 2021-10-09 09:44:51.376431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e1bad1ca49'
down_revision = '7bb76f4dedb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
