"""create tables

Revision ID: 499bd524ac18
Revises: c97cf3a47678
Create Date: 2021-10-09 14:37:32.239369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499bd524ac18'
down_revision = 'c97cf3a47678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
