"""create tables

Revision ID: 4c5b4b6d2b19
Revises: 9ed592ac84d4
Create Date: 2021-10-09 23:57:57.447891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c5b4b6d2b19'
down_revision = '9ed592ac84d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
