"""create tables

Revision ID: 51188fe17ce6
Revises: d90c9da7c513
Create Date: 2021-10-09 23:41:50.676762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51188fe17ce6'
down_revision = 'd90c9da7c513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
