"""create tables

Revision ID: 5343178b91ff
Revises: 7322abe0399d
Create Date: 2021-10-09 17:33:03.123400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5343178b91ff'
down_revision = '7322abe0399d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
