"""create tables

Revision ID: 53ac6364020d
Revises: 1473c2f03563
Create Date: 2021-10-09 23:22:29.197569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ac6364020d'
down_revision = '1473c2f03563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
