"""create tables

Revision ID: 54b40d987eda
Revises: 0e7a03c09e51
Create Date: 2021-10-09 14:58:47.990266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b40d987eda'
down_revision = '0e7a03c09e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
