"""create tables

Revision ID: 55bc34391473
Revises: 21289e12e906
Create Date: 2021-10-09 17:35:33.516180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55bc34391473'
down_revision = '21289e12e906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
