"""create tables

Revision ID: 57428e0bf75f
Revises: 094739643b2c
Create Date: 2021-10-09 14:44:28.620898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57428e0bf75f'
down_revision = '094739643b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
