"""create tables

Revision ID: 590719613023
Revises: 6a63c6356888
Create Date: 2021-10-09 15:00:40.689377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590719613023'
down_revision = '6a63c6356888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
