"""create tables

Revision ID: 5f853f1db9cc
Revises: 928bf5d2356d
Create Date: 2021-10-09 23:28:32.296194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f853f1db9cc'
down_revision = '928bf5d2356d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
