"""create tables

Revision ID: 6500d5c4631e
Revises: 51188fe17ce6
Create Date: 2021-10-09 23:42:52.628540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6500d5c4631e'
down_revision = '51188fe17ce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
