"""create tables

Revision ID: 6a402f3bd81f
Revises: f392a7f8984f
Create Date: 2021-10-09 17:23:27.459560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a402f3bd81f'
down_revision = 'f392a7f8984f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
