"""create tables

Revision ID: 6a63c6356888
Revises: 17d6667e389c
Create Date: 2021-10-09 15:00:37.970912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a63c6356888'
down_revision = '17d6667e389c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
