"""create tables

Revision ID: 6be22cdb3a93
Revises: c6c2e0d32c68
Create Date: 2021-10-09 09:45:59.346097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be22cdb3a93'
down_revision = 'c6c2e0d32c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
