"""create tables

Revision ID: 7322abe0399d
Revises: 2f2c54e511be
Create Date: 2021-10-09 17:32:05.936509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7322abe0399d'
down_revision = '2f2c54e511be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
