"""create tables

Revision ID: 74660779f5f5
Revises: 6500d5c4631e
Create Date: 2021-10-09 23:44:26.605751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74660779f5f5'
down_revision = '6500d5c4631e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
