"""create tables

Revision ID: 7ba97ba170d4
Revises: 81700a5d9f65
Create Date: 2021-10-09 17:26:41.700487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba97ba170d4'
down_revision = '81700a5d9f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
