"""create tables

Revision ID: 7bb76f4dedb3
Revises: 2c88a28a2982
Create Date: 2021-10-09 09:44:11.546580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb76f4dedb3'
down_revision = '2c88a28a2982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
