"""create tables

Revision ID: 7f77980fb6fe
Revises: 39a1e7c1a463
Create Date: 2021-10-09 15:00:56.687504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f77980fb6fe'
down_revision = '39a1e7c1a463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
