"""create tables

Revision ID: 804b29892bbb
Revises: 46936303b3ec
Create Date: 2021-10-09 11:08:01.997142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804b29892bbb'
down_revision = '46936303b3ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
