"""create tables

Revision ID: 811a68d04a9f
Revises: fad4a151fada
Create Date: 2021-10-09 09:50:43.603307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811a68d04a9f'
down_revision = 'fad4a151fada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
