"""create tables

Revision ID: 81700a5d9f65
Revises: f97ff29d1672
Create Date: 2021-10-09 17:25:36.469620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81700a5d9f65'
down_revision = 'f97ff29d1672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
