"""create tables

Revision ID: 8555d7355859
Revises: 00f6b6d3b5b7
Create Date: 2021-10-10 00:29:37.967787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8555d7355859'
down_revision = '00f6b6d3b5b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
