"""create tables

Revision ID: 86b384ec0dd9
Revises: 811a68d04a9f
Create Date: 2021-10-09 09:52:26.689511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b384ec0dd9'
down_revision = '811a68d04a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
