"""create tables

Revision ID: 8939a5ddcf73
Revises: 57df764eb75e
Create Date: 2021-10-09 17:20:23.040927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8939a5ddcf73'
down_revision = '57df764eb75e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
