"""create tables

Revision ID: 8fa0a5b769c1
Revises: 7f445dfa659e
Create Date: 2021-10-09 10:16:59.982396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa0a5b769c1'
down_revision = '7f445dfa659e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
