"""create tables

Revision ID: 91b243e4a452
Revises: 216537fa5862
Create Date: 2021-10-09 09:41:00.810913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b243e4a452'
down_revision = '216537fa5862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
