"""create tables

Revision ID: 928bf5d2356d
Revises: 53ac6364020d
Create Date: 2021-10-09 23:26:55.614900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928bf5d2356d'
down_revision = '53ac6364020d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
