"""create tables

Revision ID: 939bb09e60d1
Revises: 9d853f2f7d9b
Create Date: 2021-10-09 17:33:35.622607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939bb09e60d1'
down_revision = '9d853f2f7d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
