"""create tables

Revision ID: 96428696835d
Revises: b635fab0b750
Create Date: 2021-10-09 09:33:38.955117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96428696835d'
down_revision = 'b635fab0b750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
