"""create tables

Revision ID: 971a8f3da787
Revises: 5343178b91ff
Create Date: 2021-10-09 17:33:07.390276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971a8f3da787'
down_revision = '5343178b91ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
