"""create tables

Revision ID: 9798de7f6fcc
Revises: d0eaab3bf1b1
Create Date: 2021-10-09 14:31:22.756099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9798de7f6fcc'
down_revision = 'd0eaab3bf1b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
