"""create tables

Revision ID: 9c358fce1f33
Revises: 04efdc98c626
Create Date: 2021-10-09 18:07:04.728392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c358fce1f33'
down_revision = '04efdc98c626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('dataset_pk', sa.Integer(), nullable=False))
    op.add_column('bill', sa.Column('user_pk', sa.Integer(), nullable=False))
    op.drop_column('bill', 'dataset_id')
    op.drop_column('bill', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bill', sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('bill', 'user_pk')
    op.drop_column('bill', 'dataset_pk')
    # ### end Alembic commands ###
