"""create tables

Revision ID: 9d853f2f7d9b
Revises: eb735879a30a
Create Date: 2021-10-09 17:33:28.369102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d853f2f7d9b'
down_revision = 'eb735879a30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
