"""create tables

Revision ID: 9df161f771e4
Revises: a16d7cb0d8da
Create Date: 2021-10-09 14:41:12.195025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df161f771e4'
down_revision = 'a16d7cb0d8da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
