"""create tables

Revision ID: 9e5d8a92311c
Revises: ae87859c4283
Create Date: 2021-10-09 09:35:49.739020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5d8a92311c'
down_revision = 'ae87859c4283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
