"""create tables

Revision ID: 9ed592ac84d4
Revises: 31a5ed32fe8f
Create Date: 2021-10-09 23:54:05.695483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed592ac84d4'
down_revision = '31a5ed32fe8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
