"""create tables

Revision ID: 9ffa71ca73a4
Revises: 9c358fce1f33
Create Date: 2021-10-09 20:41:41.474828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ffa71ca73a4'
down_revision = '9c358fce1f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
