"""create tables

Revision ID: a16d7cb0d8da
Revises: cbf6f27629fe
Create Date: 2021-10-09 14:40:18.119847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16d7cb0d8da'
down_revision = 'cbf6f27629fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
