"""create tables

Revision ID: a8ba5cc5e656
Revises: 1ac7920bde5d
Create Date: 2021-10-09 14:31:30.378883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ba5cc5e656'
down_revision = '1ac7920bde5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
