"""create tables

Revision ID: ac2da1b556de
Revises: d0e13d155a5f
Create Date: 2021-10-09 10:19:20.956537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac2da1b556de'
down_revision = 'd0e13d155a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
