"""create tables

Revision ID: ac96de5d6d41
Revises: 3028b658035f
Create Date: 2021-10-10 00:00:23.216029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac96de5d6d41'
down_revision = '3028b658035f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
