"""create tables

Revision ID: ad28452cdf05
Revises: d4be07000276
Create Date: 2021-10-09 09:30:02.851087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad28452cdf05'
down_revision = 'd4be07000276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
