"""create tables

Revision ID: af72790afa51
Revises: b4362cd850fc
Create Date: 2021-10-09 14:32:02.919530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af72790afa51'
down_revision = 'b4362cd850fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
