"""create tables

Revision ID: b18996f507fd
Revises: 57428e0bf75f
Create Date: 2021-10-09 14:47:34.992894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18996f507fd'
down_revision = '57428e0bf75f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
