"""create tables

Revision ID: b4362cd850fc
Revises: 07d7d6ac5180
Create Date: 2021-10-09 14:31:47.836766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4362cd850fc'
down_revision = '07d7d6ac5180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
