"""create tables

Revision ID: b635fab0b750
Revises: c2bfd363babf
Create Date: 2021-10-09 09:32:59.953340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b635fab0b750'
down_revision = 'c2bfd363babf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
