"""create tables

Revision ID: b8ca9ee43a99
Revises: 0b723ec44f7f
Create Date: 2021-10-09 10:25:24.077495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ca9ee43a99'
down_revision = '0b723ec44f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
