"""create tables

Revision ID: c07aed9811c6
Revises: 9798de7f6fcc
Create Date: 2021-10-09 14:31:25.090002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c07aed9811c6'
down_revision = '9798de7f6fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
