"""create tables

Revision ID: c12f482425ef
Revises: cafb6e849f4e
Create Date: 2021-10-09 09:25:43.230951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12f482425ef'
down_revision = 'cafb6e849f4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
