"""create tables

Revision ID: c15e31ede869
Revises: 7f77980fb6fe
Create Date: 2021-10-09 15:01:25.749634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15e31ede869'
down_revision = '7f77980fb6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
