"""create tables

Revision ID: c1d90357bf03
Revises: e7e50a99d4a0
Create Date: 2021-10-10 00:10:07.037436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d90357bf03'
down_revision = 'e7e50a99d4a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
