"""create tables

Revision ID: c2bfd363babf
Revises: e117bc46e589
Create Date: 2021-10-09 09:32:10.895435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2bfd363babf'
down_revision = 'e117bc46e589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
