"""create tables

Revision ID: c4a9080091de
Revises: 8939a5ddcf73
Create Date: 2021-10-09 17:21:18.656350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a9080091de'
down_revision = '8939a5ddcf73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
