"""create tables

Revision ID: c50b73d3c26b
Revises: cf1414c8b72e
Create Date: 2021-10-09 14:54:49.832337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50b73d3c26b'
down_revision = 'cf1414c8b72e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
