"""create tables

Revision ID: c6c2e0d32c68
Revises: 48e1bad1ca49
Create Date: 2021-10-09 09:45:07.592026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c2e0d32c68'
down_revision = '48e1bad1ca49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
