"""create tables

Revision ID: c739473f10b9
Revises: 14179c0500b4
Create Date: 2021-10-09 17:19:15.127132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c739473f10b9'
down_revision = '14179c0500b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
