"""create tables

Revision ID: c97cf3a47678
Revises: f9152f515bf7
Create Date: 2021-10-09 14:35:44.849364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c97cf3a47678'
down_revision = 'f9152f515bf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
