"""create tables

Revision ID: ca8b062eb782
Revises: 1c9685fe0e47
Create Date: 2021-10-09 17:33:19.073305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8b062eb782'
down_revision = '1c9685fe0e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
