"""create tables

Revision ID: cafb6e849f4e
Revises: 5c6d4f826a6c
Create Date: 2021-10-09 09:25:02.743823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cafb6e849f4e'
down_revision = '5c6d4f826a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
