"""create tables

Revision ID: cbf6f27629fe
Revises: 499bd524ac18
Create Date: 2021-10-09 14:39:13.441072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf6f27629fe'
down_revision = '499bd524ac18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
