"""create tables

Revision ID: cd2c60df7506
Revises: 08fc9a7623b6
Create Date: 2021-10-09 10:22:39.811596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd2c60df7506'
down_revision = '08fc9a7623b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
