"""create tables

Revision ID: cf1414c8b72e
Revises: 0f6f49a718b0
Create Date: 2021-10-09 14:54:18.974665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf1414c8b72e'
down_revision = '0f6f49a718b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
