"""create tables

Revision ID: cf70ecc07a62
Revises: 91b243e4a452
Create Date: 2021-10-09 09:41:52.797002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf70ecc07a62'
down_revision = '91b243e4a452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
