"""create tables

Revision ID: d0da467bf1d0
Revises: a8ba5cc5e656
Create Date: 2021-10-09 14:31:34.024321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0da467bf1d0'
down_revision = 'a8ba5cc5e656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
