"""create tables

Revision ID: d0e13d155a5f
Revises: 8fa0a5b769c1
Create Date: 2021-10-09 10:18:06.471964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e13d155a5f'
down_revision = '8fa0a5b769c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
