"""create tables

Revision ID: d0eaab3bf1b1
Revises: 804b29892bbb
Create Date: 2021-10-09 14:31:20.388567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0eaab3bf1b1'
down_revision = '804b29892bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
