"""create tables

Revision ID: d5e0b0feece6
Revises: f2d7d29d5469
Create Date: 2021-10-09 23:39:29.063802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e0b0feece6'
down_revision = 'f2d7d29d5469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
