"""create tables

Revision ID: d74f7939a7f7
Revises: 06f02c42ad46
Create Date: 2021-10-09 17:19:34.894567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd74f7939a7f7'
down_revision = '06f02c42ad46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
