"""create tables123

Revision ID: d90c9da7c513
Revises: d5e0b0feece6
Create Date: 2021-10-09 23:40:15.075280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90c9da7c513'
down_revision = 'd5e0b0feece6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
