"""create tables

Revision ID: d97561eacfc1
Revises: f2e01dfb95da
Create Date: 2021-10-09 17:36:04.193160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97561eacfc1'
down_revision = 'f2e01dfb95da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
