"""create tables

Revision ID: dacb50e8ab1d
Revises: 5f853f1db9cc
Create Date: 2021-10-09 23:30:27.536228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dacb50e8ab1d'
down_revision = '5f853f1db9cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
