"""create tables

Revision ID: dbf599af193b
Revises: 6be22cdb3a93
Create Date: 2021-10-09 09:47:01.946017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf599af193b'
down_revision = '6be22cdb3a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
