"""create tables

Revision ID: de29361780fb
Revises: fef749ec032f
Create Date: 2021-10-09 15:18:17.696741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de29361780fb'
down_revision = 'fef749ec032f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
