"""create tables

Revision ID: deab80972e35
Revises: 3ff1fd7a973c
Create Date: 2021-10-09 17:18:56.939225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deab80972e35'
down_revision = '3ff1fd7a973c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
