"""create tables

Revision ID: e117bc46e589
Revises: ad28452cdf05
Create Date: 2021-10-09 09:30:39.583648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e117bc46e589'
down_revision = 'ad28452cdf05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
