"""create tables

Revision ID: e1a850ee2cf3
Revises: 26b148e8ceef
Create Date: 2021-10-09 22:42:33.388254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a850ee2cf3'
down_revision = '26b148e8ceef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
