"""create tables

Revision ID: e3aa88ca1861
Revises: 345cfc88f5a8
Create Date: 2021-10-09 23:33:26.668452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3aa88ca1861'
down_revision = '345cfc88f5a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
