"""create tables

Revision ID: e7e50a99d4a0
Revises: ac96de5d6d41
Create Date: 2021-10-10 00:06:17.221511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e50a99d4a0'
down_revision = 'ac96de5d6d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
