"""create tables

Revision ID: e83b4eec4f2a
Revises: 47b0416c7220
Create Date: 2021-10-09 17:38:19.182352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83b4eec4f2a'
down_revision = '47b0416c7220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
