"""create tables

Revision ID: ea577249414d
Revises: e83b4eec4f2a
Create Date: 2021-10-09 17:39:25.944809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea577249414d'
down_revision = 'e83b4eec4f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
