"""create tables

Revision ID: eb735879a30a
Revises: ca8b062eb782
Create Date: 2021-10-09 17:33:23.607699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb735879a30a'
down_revision = 'ca8b062eb782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
