"""create tables

Revision ID: ed486f37e4cf
Revises: f777d0f9da29
Create Date: 2021-10-09 17:34:04.953663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed486f37e4cf'
down_revision = 'f777d0f9da29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
