"""create tables

Revision ID: f2d7d29d5469
Revises: e3aa88ca1861
Create Date: 2021-10-09 23:38:17.244223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d7d29d5469'
down_revision = 'e3aa88ca1861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
