"""create tables

Revision ID: f2dbb3dba1d2
Revises: deab80972e35
Create Date: 2021-10-09 17:19:02.485563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2dbb3dba1d2'
down_revision = 'deab80972e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
