"""create tables

Revision ID: f2e01dfb95da
Revises: 0366586feda1
Create Date: 2021-10-09 17:35:59.069235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e01dfb95da'
down_revision = '0366586feda1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
