"""create tables

Revision ID: f392a7f8984f
Revises: c4a9080091de
Create Date: 2021-10-09 17:22:23.377554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f392a7f8984f'
down_revision = 'c4a9080091de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
