"""create tables

Revision ID: f50071b9e8ad
Revises: d97561eacfc1
Create Date: 2021-10-09 17:36:08.184680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50071b9e8ad'
down_revision = 'd97561eacfc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
