"""create tables

Revision ID: f777d0f9da29
Revises: 939bb09e60d1
Create Date: 2021-10-09 17:33:47.861471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f777d0f9da29'
down_revision = '939bb09e60d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
