"""create tables

Revision ID: f9029adeb419
Revises: af72790afa51
Create Date: 2021-10-09 14:32:30.416497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9029adeb419'
down_revision = 'af72790afa51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
