"""create tables

Revision ID: f9152f515bf7
Revises: f9029adeb419
Create Date: 2021-10-09 14:34:46.284852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9152f515bf7'
down_revision = 'f9029adeb419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
