"""create tables

Revision ID: f97ff29d1672
Revises: 6a402f3bd81f
Create Date: 2021-10-09 17:24:32.253318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97ff29d1672'
down_revision = '6a402f3bd81f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
