"""create tables

Revision ID: fad4a151fada
Revises: 0733dfffc200
Create Date: 2021-10-09 09:49:16.669934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad4a151fada'
down_revision = '0733dfffc200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
