"""create tables

Revision ID: fef749ec032f
Revises: c15e31ede869
Create Date: 2021-10-09 15:14:52.346242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef749ec032f'
down_revision = 'c15e31ede869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
